# taken from https://github.com/ldionne/hana/blob/master/.travis.yml

language: c++
os: linux
sudo: false

matrix:
  include:

    - env: COMPILER=clang CLANG_VERSION=3.5
      addons: &clang35
        apt:
          packages:
            - clang-3.5
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - env: COMPILER=clang CLANG_VERSION=3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

before_script:
  ############################################################################
  # Setup the build directory
  ############################################################################
  - if [[ $COMPILER = clang ]] ; then export CXX="clang++-${CLANG_VERSION}" ; fi
  - if [[ $COMPILER = gcc ]]   ; then export CXX="g++-${GCC_VERSION}" ; fi
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=${CXX} ..

script:
  - export CTEST_PARALLEL_LEVEL=2
  - make && make test -k -j3
