# taken from https://github.com/ldionne/hana/blob/master/.travis.yml

language: c++
compiler:
  - clang
  - gcc
os: linux
sudo: false

addons:
  apt:
    packages:
    - valgrind
    - libboost-all-dev

before_script:
  ############################################################################
  # Setup the build directory
  ############################################################################
  - mkdir build
  - cd build
  - cmake ..

script:
  - export CTEST_PARALLEL_LEVEL=2
  - make test -k -j3
