# taken from https://github.com/ldionne/hana/blob/master/.travis.yml

language: c++
os: linux
sudo: false

matrix:
  include:
    - env: CLANG_VERSION=3.5
      addons: &clang35
        apt:
          packages:
            - clang-3.5
            - valgrind
            - libboost-all-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

before_script:
  ############################################################################
  # Setup the build directory
  ############################################################################
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=clang++-${CLANG_VERSION} ..

script:
  - export CTEST_PARALLEL_LEVEL=2
  - make && make test -k -j3
